"use strict";var p=Object.defineProperty;var A=Object.getOwnPropertyDescriptor;var T=Object.getOwnPropertyNames;var H=Object.prototype.hasOwnProperty;var C=(e,n)=>{for(var a in n)p(e,a,{get:n[a],enumerable:!0})},L=(e,n,a,E)=>{if(n&&typeof n=="object"||typeof n=="function")for(let r of T(n))!H.call(e,r)&&r!==a&&p(e,r,{get:()=>n[r],enumerable:!(E=A(n,r))||E.enumerable});return e};var h=e=>L(p({},"__esModule",{value:!0}),e);var I={};C(I,{default:()=>O});module.exports=h(I);var t=require("@raycast/api");var s={a:["Alfa","AL-FAH"],b:["Bravo","BRAH-VOH"],c:["Charlie","CHAR-LEE"],d:["Delta","DELL-TAH"],e:["Echo","ECK-OH"],f:["Foxtrot","FOKS-TROT"],g:["Golf","GOLF"],h:["Hotel","HOH-TEL"],i:["India","IN-DEE-AH"],j:["Juliett","JEW-LEE-ETT"],k:["Kilo","KEY-LOH"],l:["Lima","LEE-MAH"],m:["Mike","MIKE"],n:["November","NO-VEM-BER"],o:["Oscar","OSS-CAH"],p:["Papa","PAH-PAH"],q:["Quebec","KEH-BECK"],r:["Romeo","ROW-ME-OH"],s:["Sierra","SEE-AIR-RAH"],t:["Tango","TANG-GO"],u:["Uniform","YOU-NEE-FORM"],v:["Victor","VIK-TAH"],w:["Whiskey","WISS-KEY"],x:["X-ray","ECKS-RAY"],y:["Yankee","YANG-KEY"],z:["Zulu","ZOO-LOO"],1:["One","WUN"],2:["Two","TOO"],3:["Three","TREE"],4:["Four","FOW-ER"],5:["Five","FIFE"],6:["Six","SIX"],7:["Seven","SEV-EN"],8:["Eight","AIT"],9:["Nine","NIN-ER"],0:["Zero","ZEE-RO"]};var i=require("react/jsx-runtime"),u=`\r
\r
`;function O(e){let n=(e.arguments.Term||e.fallbackText||"").trim();if(!n)return(0,i.jsx)(t.List,{children:(0,i.jsx)(t.List.EmptyView,{title:"Error",description:"Please enter text to spell",icon:t.Icon.Warning})});let E=n.split(" ").map(l=>[...l].map(o=>(o=o.toLowerCase(),o in s?{character:o,telephony:s[o][0],pronunciation:s[o][1]}:{character:o,telephony:o,pronunciation:o}))),r=E.flatMap(l=>l.map(o=>o.telephony).join(" ")).join(u),c=E.flatMap(l=>l.map(o=>o.pronunciation).join(" ")).join(u),m=`
  ## Telephony
  ${r}

  ## Pronunciation
  ${c}
  `;return(0,i.jsx)(t.Detail,{navigationTitle:n,markdown:m,actions:(0,i.jsxs)(t.ActionPanel,{children:[(0,i.jsx)(t.Action.CopyToClipboard,{title:"Copy Telephony to Clipboard",content:r}),(0,i.jsx)(t.Action.CopyToClipboard,{title:"Copy Pronunciation to Clipboard",content:c})]})})}
