"use strict";var A=Object.defineProperty;var q=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var G=Object.prototype.hasOwnProperty;var V=(r,t)=>{for(var u in t)A(r,u,{get:t[u],enumerable:!0})},B=(r,t,u,s)=>{if(t&&typeof t=="object"||typeof t=="function")for(let a of P(t))!G.call(r,a)&&a!==u&&A(r,a,{get:()=>t[a],enumerable:!(s=q(t,a))||s.enumerable});return r};var M=r=>B(A({},"__esModule",{value:!0}),r);var Y={};V(Y,{default:()=>k});module.exports=M(Y);var e=require("@raycast/api"),w=require("react");var n=require("@raycast/api"),p=require("react");var $={title:"\u{1F6A8}"},Q={title:"\u{1F50D}",message:"Answering your question"},E={title:"\u2705",message:"Answer has been saved!"};function x(){return`q-${Date.now()}`}function H(r,t){return`The following text is the content of a video. Refer to it as video. You already summarized it for the person asking a question. Answer with a list starting with a fitting emoji. Ignore Sponsor Segments and Video Sponsors.
  
  Format:

  [Emoji] [List Item] &nbsp;&nbsp;
  
  Here is the transcript: ${t}. This is the question: ${r}`}var m=require("react/jsx-runtime");function T({transcript:r,questions:t,onQuestionsUpdate:u}){let[s,a]=(0,p.useState)(""),[l,g]=(0,p.useState)(t[0]?.id??""),[c,o]=(0,p.useState)(t);(0,p.useEffect)(()=>{u&&u(c)},[c,u]);let f=(0,p.useCallback)(i=>{o(i)},[]),S=async()=>{if(!s)return;let i=x(),d=s,L=await(0,n.showToast)({style:n.Toast.Style.Animated,title:Q.title,message:Q.message}),D=n.AI.ask(H(d,r)),C=[{id:i,question:d,answer:""},...c];f(C),a("");let _=!0;D.on("data",F=>{_&&(L.show(),_=!1),o(v=>v.map(h=>h.id===i?{...h,answer:h.answer+F}:h))}),D.finally(()=>{L.hide(),g(i)})},O=()=>`${c.length?`Questions:
${c.map(d=>`Q: ${d.question}
A: ${d.answer}`).join(`

`)}`:""}`,U=()=>{let i=c.find(d=>d.id===l);return i?i.id===c[0]?.id?i.answer:`Q: ${i.question}
A: ${i.answer}`:""};return(0,m.jsx)(n.List,{filtering:!1,isShowingDetail:!0,navigationTitle:"Additional Questions",onSearchTextChange:a,searchText:s,searchBarPlaceholder:"Ask another question",selectedItemId:l,searchBarAccessory:(0,m.jsxs)(n.ActionPanel,{children:[(0,m.jsx)(n.Action.SubmitForm,{onSubmit:S}),(0,m.jsx)(n.Action.CopyToClipboard,{title:"Copy Selected Answer",content:U()}),(0,m.jsx)(n.Action.CopyToClipboard,{title:"Copy All Q&A",content:O()})]}),children:c.map(i=>(0,m.jsx)(n.List.Item,{title:i.question,detail:(0,m.jsx)(n.List.Item.Detail,{markdown:i.answer}),id:i.id},i.id))})}var I=require("@raycast/api"),R="youtube-summary-",b="youtube-summary-keys",N=()=>{let r=async s=>{let a=`${s.id}-${s.aiService}`;await I.LocalStorage.setItem(`${R}${a}`,JSON.stringify(s));let l=await u();l.includes(a)||(l.unshift(a),await I.LocalStorage.setItem(b,JSON.stringify(l)))},t=async()=>{let s=await u();return(await Promise.all(s.map(async l=>{let g=await I.LocalStorage.getItem(`${R}${l}`);if(!g)return null;let c=JSON.parse(g);return c.createdAt=new Date(c.createdAt),c}))).filter(l=>l!==null)},u=async()=>{let s=await I.LocalStorage.getItem(b);return s?JSON.parse(s):[]};return{addToHistory:r,getHistory:t}};var y=require("react/jsx-runtime");function k(){let[r,t]=(0,w.useState)([]),[u,s]=(0,w.useState)(!0),{getHistory:a,addToHistory:l}=N();(0,w.useEffect)(()=>{c()},[]);async function g(o,f){try{let S={...o,questions:f,createdAt:new Date};await l(S),await c(),await(0,e.showToast)({style:e.Toast.Style.Success,title:E.title,message:E.message})}catch(S){await(0,e.showToast)({style:e.Toast.Style.Failure,title:$.title,message:String(S)})}}async function c(){try{let o=await a();t(o)}catch(o){await(0,e.showToast)({style:e.Toast.Style.Failure,title:"Failed to load history",message:String(o)})}finally{s(!1)}}return(0,y.jsx)(e.List,{isLoading:u,children:r.map(o=>(0,y.jsx)(e.List.Item,{icon:e.Icon.Video,title:o.title,subtitle:new Date(o.createdAt).toLocaleDateString(),accessories:[{text:o.aiService}],actions:(0,y.jsx)(e.ActionPanel,{children:(0,y.jsx)(e.Action.Push,{icon:e.Icon.Document,title:"Check Details",target:(0,y.jsx)(T,{transcript:o.summary,questions:o.questions,onQuestionsUpdate:f=>g(o,f)})})})},`${o.id}-${o.aiService}`))})}
