"use strict";var P=Object.create;var f=Object.defineProperty;var R=Object.getOwnPropertyDescriptor;var A=Object.getOwnPropertyNames;var F=Object.getPrototypeOf,O=Object.prototype.hasOwnProperty;var L=(r,t)=>{for(var i in t)f(r,i,{get:t[i],enumerable:!0})},u=(r,t,i,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let e of A(t))!O.call(r,e)&&e!==i&&f(r,e,{get:()=>t[e],enumerable:!(n=R(t,e))||n.enumerable});return r};var G=(r,t,i)=>(i=r!=null?P(F(r)):{},u(t||!r||!r.__esModule?f(i,"default",{value:r,enumerable:!0}):i,r)),K=r=>u(f({},"__esModule",{value:!0}),r);var k={};L(k,{default:()=>N});module.exports=K(k);var p=require("react"),a=require("@raycast/api"),b=require("child_process"),T=G(require("node:path"));var h=require("fs"),E=G(require("path")),v=require("@raycast/api"),y=E.default.join(v.environment.supportPath,"memory.json");(async()=>{try{await h.promises.access(y)}catch(r){if(r instanceof Error&&"code"in r&&r.code==="ENOENT")await h.promises.writeFile(y,"");else throw r}})();var w=class{async loadGraph(){try{return(await h.promises.readFile(y,"utf-8")).split(`
`).filter(n=>n.trim()!=="").reduce((n,e)=>{let o=JSON.parse(e);return o.type==="entity"&&n.entities.push(o),o.type==="relation"&&n.relations.push(o),n},{entities:[],relations:[]})}catch(t){if(t instanceof Error&&"code"in t&&t.code==="ENOENT")return{entities:[],relations:[]};throw t}}async saveGraph(t){console.log(t);let i=[...t.entities.map(n=>JSON.stringify({type:"entity",...n})),...t.relations.map(n=>JSON.stringify({type:"relation",...n}))];await h.promises.writeFile(y,i.join(`
`))}async createEntities(t){let i=await this.loadGraph(),n=t.filter(e=>!i.entities.some(o=>o.name===e.name));return i.entities.push(...n),await this.saveGraph(i),n}async createRelations(t){let i=await this.loadGraph(),n=t.filter(e=>!i.relations.some(o=>o.from===e.from&&o.to===e.to&&o.relationType===e.relationType));return i.relations.push(...n),await this.saveGraph(i),n}async addObservations(t){let i=await this.loadGraph(),n=t.map(e=>{let o=i.entities.find(s=>s.name===e.entityName);if(!o)throw new Error(`Entity with name ${e.entityName} not found`);let m=e.contents.filter(s=>!o.observations.includes(s));return o.observations.push(...m),{entityName:e.entityName,addedObservations:m}});return await this.saveGraph(i),n}async deleteEntities(t){let i=await this.loadGraph();i.entities=i.entities.filter(n=>!t.includes(n.name)),i.relations=i.relations.filter(n=>!t.includes(n.from)&&!t.includes(n.to)),await this.saveGraph(i)}async deleteObservations(t){let i=await this.loadGraph();t.forEach(n=>{let e=i.entities.find(o=>o.name===n.entityName);e&&(e.observations=e.observations.filter(o=>!n.observations.includes(o)))}),await this.saveGraph(i)}async deleteRelations(t){let i=await this.loadGraph();i.relations=i.relations.filter(n=>!t.some(e=>n.from===e.from&&n.to===e.to&&n.relationType===e.relationType)),await this.saveGraph(i)}async readGraph(){return this.loadGraph()}async searchNodes(t){let i=await this.loadGraph(),n=i.entities.filter(s=>s.name.toLowerCase().includes(t.toLowerCase())||s.entityType.toLowerCase().includes(t.toLowerCase())||s.observations.some(l=>l.toLowerCase().includes(t.toLowerCase()))),e=new Set(n.map(s=>s.name)),o=i.relations.filter(s=>e.has(s.from)&&e.has(s.to));return{entities:n,relations:o}}async openNodes(t){let i=await this.loadGraph(),n=i.entities.filter(s=>t.includes(s.name)),e=new Set(n.map(s=>s.name)),o=i.relations.filter(s=>e.has(s.from)&&e.has(s.to));return{entities:n,relations:o}}},g=new w;var S=require("@raycast/api"),c=require("react/jsx-runtime"),$=T.default.join(S.environment.supportPath,"memory.json");function N(){let[r,t]=(0,p.useState)(null),[i,n]=(0,p.useState)(!0);return(0,p.useEffect)(()=>{async function e(){try{let o=await g.readGraph();t(o)}catch(o){(0,a.showToast)(a.Toast.Style.Failure,"Failed to load memory",String(o))}finally{n(!1)}}e()},[]),(0,c.jsxs)(a.List,{isLoading:i,isShowingDetail:!(r&&r.entities.length===0),searchBarPlaceholder:"Filter Entities",children:[r&&r.entities.length===0&&(0,c.jsx)(a.List.EmptyView,{icon:a.Icon.Bookmark,title:"Memory is Empty",description:"Talk to Raycast AI to get started"}),r&&r.entities.map(e=>{let o=r.relations.filter(l=>l.from===e.name),m=r.relations.filter(l=>l.to===e.name),s=`# ${e.name} (${e.entityType})

`;return s+=`## Observations
`,e.observations.length===0?s+=`None
`:e.observations.forEach(l=>{s+=`- ${l}
`}),s+=`
## Relations
`,o.length===0&&m.length===0?s+=`None
`:(o.forEach(l=>{s+=`- Outgoing: [${l.relationType}] \u2192 ${l.to}
`}),m.forEach(l=>{s+=`- Incoming: [${l.relationType}] \u2190 ${l.from}
`})),(0,c.jsx)(a.List.Item,{title:e.name,subtitle:e.entityType,accessories:[{text:`${e.observations.length} obs`}],detail:(0,c.jsx)(a.List.Item.Detail,{markdown:s}),actions:(0,c.jsx)(a.ActionPanel,{children:(0,c.jsxs)(a.ActionPanel.Section,{children:[(0,c.jsx)(a.Action,{title:"Reveal Memory File in Finder",icon:a.Icon.Finder,onAction:()=>{(0,b.exec)(`open -R "${$}"`,l=>{l&&(0,a.showToast)(a.Toast.Style.Failure,"Failed to reveal file",l.message)})}}),(0,c.jsx)(a.Action,{title:"Refresh Graph",icon:a.Icon.Repeat,onAction:async()=>{n(!0);try{let l=await g.readGraph();t(l)}catch(l){(0,a.showToast)(a.Toast.Style.Failure,"Error refreshing graph",String(l))}finally{n(!1)}}}),(0,c.jsx)(a.Action,{title:"Delete Entity",icon:a.Icon.Trash,style:a.Action.Style.Destructive,onAction:async()=>{await(0,a.confirmAlert)({title:"Are you sure?",message:"Deleting this entity will permanently remove it along with its observations and relations.",icon:a.Icon.Trash,primaryAction:{title:"Delete Entity",style:a.Alert.ActionStyle.Destructive,onAction:async()=>{try{await g.deleteEntities([e.name]),t(l=>l&&{entities:l.entities.filter(d=>d.name!==e.name),relations:l.relations.filter(d=>d.from!==e.name&&d.to!==e.name)}),(0,a.showToast)(a.Toast.Style.Success,"Entity deleted")}catch(l){(0,a.showToast)(a.Toast.Style.Failure,"Failed to delete entity",String(l))}}}})}})]})})},e.name)})]})}
